### ISSUE TITLE
Open Source License

### ISSUE THREAD

**Issue by jonaharagon** [scidsg/relaylove#5]
**Is your feature request related to a problem? Please describe.**
I am interested in cloning this repository and potentially making modifications, and don't feel comfortable doing so with unclear/[nonexistent project licensing](https://choosealicense.com/no-permission/#for-users). If that is not allowed that is also fine, but the "Clone This Project" button on the site suggests to me that this is an oversight.

**Describe the solution you'd like**
I would like this repository licensed under the [MIT License](https://choosealicense.com/licenses/mit/) or CC0 (or anything similar you feel is appropriate).

**Describe alternatives you've considered**
n/a

**Additional context**
Also, ideally you would not use a Creative Commons license like the design-system repo has, which I think is a [questionable choice](https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software).

**Comment by glenn-sorrentino** [comment]
Thanks for catching this. Added here: https://github.com/scidsg/relaylove/blob/main/LICENSE

**Comment by glenn-sorrentino** [comment]
Also updated the design system license.
